Sources/IKS/IKS/Controllers/EventController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class EventController : Controller
    {
        public IEventManager eventManager { get; set; }
        public EventController(IEventManager eventManager)
        {
            this.eventManager = eventManager;
        }
        // GET: Concert
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            EventModel model;
            if (id.HasValue)
                model = eventManager.GetEvent(id.Value);
            else
                model = new EventModel();

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit( EventModel model)
        {
            if (ModelState.IsValid)
            {
                eventManager.Save(model);
            }
            return View(model);
        }
        public ActionResult PerformanceSelect(Guid eventId)
        {
            var model = new MainSelectPerformanceViewModel()
            {
                EventId = eventId
            };
            return PartialView(model);
        }
        public void AddPerformances(Guid eventId, string performanceIds)
        {
            eventManager.AddPerformances(eventId, performanceIds);
        }
    }
}

Sources/IKS/IKS/Controllers/PerformanceController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class PerformanceController : Controller
    {
        public IPerformanceManager perfManager { get; set; }
        public PerformanceController(IPerformanceManager perfManager)
        {
            this.perfManager = perfManager;
        }
        // GET: Performance
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit(Guid? id, Guid? eventId)
        {
            PerformanceModel model;
            if (id.HasValue)
                model = perfManager.GetPerformance(id.Value);
            else
                model = new PerformanceModel(eventId);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(PerformanceModel model)
        {
            if (ModelState.IsValid)
            {
                perfManager.Save(model);
                //return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public void Delete(Guid id, Guid? eventId)
        {
            if (ModelState.IsValid)
            {
                perfManager.Delete(id, eventId);
                //return RedirectToAction("Index");
            }
        }
    }
}

Sources/IKS/IKS/Views/Event/Edit.cshtml
@model IKS.Models.EventModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.EventId)
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<div class="modal fade" id="perfSelectModal" role="dialog" data-url="@Url.Action("PerformanceSelect", "Event")">
    @Html.Partial("PerformanceSelect")
</div>
<div class="well">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <button data-toggle="modal" data-target="#perfSelectModal" class="btn btn-info">Add Performances</button>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Edit", "Performance", new { eventId = Model.EventId })'">Add New Performance</button>
</div>

@Html.MVCGrid(nameof(IKS.Grids.PerformanceGrid), new { eventId=Model.EventId})

<script type="text/javascript">
    
    window.SetPerformances = SetPerformances;
    
    function AddPerformances() {
        var url = $("#perfSelectModal").data('url');
        $.get(url, function (data) {
            $("#perfSelectModal").html(data);
            $("#perfSelectModal").html('show');
        })
    }
    function BackButton() {
        var url = '@Url.Action("Index", "Event")';

        if ('@Model.EventId' != null)
            url = '@Url.Action("Edit", "Event", new { id = Model.EventId })';
            //location.href = '@Url.Action("Edit", "Event", new { id = Model.EventId })';
        

        window.location.href = url;
    }
    function SetPerformances(p) {
        alert('Added performances');
        $.post('@Url.Action("AddPerformances", new { eventId = Model.EventId})&performanceIds=' + p);
        }
    @*function DeletePerformance(performanceId, eventId) {
        $.post('@Url.Action("Delete", new { eventId = Model.EventId})&performanceId=' + performanceId + eventId != null ? '&eventId=' + eventId : '');

        }*@
    function DeletePerformance(url) {
        $.post(url);

    }
</script>

Sources/IKS/IKS/Views/Event/Index.cshtml
<h1>Koncerti</h1>

@Html.MVCGrid(nameof(IKS.Grids.EventGrid))

<script type="text/javascript">

        jQuery(document).ready(function($){
            MVCGrid.reloadGrid('@MVCGridConfig.EventGrid');
        });

</script>

Sources/IKS/IKS/Views/Event/PerformanceSelect.cshtml
@{
    Layout = "~/Views/Shared/ModalLayout.cshtml";
    ViewBag.Title = "Select performances";
}
@Model IKS.Models.MainSelectPerformanceViewModel
@Html.MVCGrid(nameof(IKS.Grids.SelectPerformanceGrid), new { eventId= Model.EventId})

<script type="text/javascript">
    var selItemList = "selectedItems"

    jQuery(document).ready(function ($) {
        localStorage.removeItem(selItemList)
    });

    function ModalOK() {
        var selItems = localStorage.getItem(selItemList);
        var itemList = selItems.split(',');
        for (var i = 0; i < itemList.length; i++) {
            var val = itemList[i];
            itemList[i] = val.replace('cbx_', '');
        }
        window.parent.SetPerformances(itemList.join(','));
    }
    function CheckboxChanged(e) {
        var selItems = localStorage.getItem(selItemList);
        if (e.checked) {

            if (selItems == null || selItems == '')
                localStorage.setItem(selItemList, e.id);
            else {
                var itemList = selItems.split(',');
                if (!itemList.find(element => element == e.id)) {
                    localStorage.setItem(selItemList, selItems + ',' + e.id);
                }
            }
        }
        else if (selItems != null) {
            //remove id from selected
            var itemList = selItems.split(',');
            for (var i = 0; i < itemList.length; i++) {
                if (itemList[i] === e.id) {
                    itemList.splice(i, 1);
                    i--;
                }
            }
            localStorage.setItem(selItemList, itemList.join(','));

        }
    }
</script>