Sources/IKS/IKS/Controllers/ItemController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class ItemController : Controller
    {
        public IItemManager itemManager { get; set; }
        public ItemController(IItemManager itemManager)
        {
            this.itemManager = itemManager;
        }
        public ActionResult Index()
        {
            ViewBag.ColumnVisibility = JsonConvert.SerializeObject(GetColumnVisibility().Data);
            return View();
        }
        [HttpGet]
        public ActionResult Edit(Guid? id, Guid? parentId)
        {
            ItemModel model;
            if (id.HasValue)
                model = itemManager.GetItem(id.Value);
            else
                model = new ItemModel();

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ItemModel model)
        {
            if (ModelState.IsValid)
            {
                itemManager.Save(model);
            }
            return View(model);
        }
        public ActionResult AddItem()
        {
            return RedirectToAction(nameof(Edit), new { id = Guid.Empty });
        }

        public JsonResult GetColumnVisibility()
        {
            
            var item = new
            {
                Code = true,
                Name = true,
                Description = false
            };
            return Json(item);
        }
    }
}

Sources/IKS/IKS/Views/Item/Edit.cshtml
@model IKS.Models.ItemModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.ActionLink("+Jauns Tērps", "Edit", "Item", new { id="", parentId=Model.ItemId }, new { @class = "btn btn-default" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ItemId)
    @Html.HiddenFor(model => model.Status)
    @Html.HiddenFor(model => model.IsNew)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Code)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Saglabāt</button>
    <hr />
    @Html.MVCGrid(nameof(IKS.Grids.ItemGrid), new { parentId = Model.ItemId })
}

<script>
    MVCGrid.setColumnVisibility()
</script>

Sources/IKS/IKS/Views/Item/Index.cshtml
@Html.AntiForgeryToken()
<div class="well">
    @Html.ActionLink("+Jauns Tērps", "Edit", "Item", new { @class = "btn btn-default" })
</div>
@Html.MVCGrid(nameof(IKS.Grids.ItemGrid))
@*<script type="text/javascript">
    $(document).ready(function () {
        MVCGrid.setColumnVisibility('ColumnVisibilityGrid', @Html.Raw(ViewBag.ColumnVisibility));
    });

</script>*@