Sources/IKS/IKS/Controllers/EventController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class EventController : Controller
    {
        public IEventManager eventManager { get; set; }
        public EventController(IEventManager eventManager)
        {
            this.eventManager = eventManager;
        }
        // GET: Concert
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            EventModel model;
            if (id.HasValue)
                model = eventManager.GetEvent(id.Value);
            else
                model = new EventModel();

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit( EventModel model)
        {
            if (ModelState.IsValid)
            {
                eventManager.Save(model);
            }
            return View(model);
        }
        public ActionResult PerformanceSelect(Guid eventId)
        {
            var model = new MainSelectPerformanceViewModel()
            {
                EventId = eventId
            };
            return PartialView(model);
        }
        public void AddPerformances(Guid eventId, string performanceIds)
        {
            eventManager.AddPerformances(eventId, performanceIds);
        }
    }
}

Sources/IKS/IKS/Controllers/HandoverReturnController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class HandoverReturnController : Controller
    {
        public IUserManager userManager { get; set; }
        public IHandoverReturnManager hrManager { get; set; }
        public IItemManager itemManager { get; set; }
        public HandoverReturnController(IUserManager userManager, IHandoverReturnManager hrManager, IItemManager itemManager)
        {
            this.userManager = userManager;
            this.hrManager = hrManager;
            this.itemManager = itemManager;
        }
        public ActionResult Index(Guid? id = null)
        {
            UserModel userModel = null;
            if(id.HasValue)
                userManager.GetUser(id.Value);
            else
                userModel = userManager.GetAllUsers().FirstOrDefault();

            var model = new HandoverModel() { User = userModel };
            return View(model);
        }
        public JsonResult Handover(Guid userId, string itemIds)
        {
            hrManager.AddItems(userId, itemIds);
            return Json("");
        }
        public JsonResult Return(Guid userId, string itemIds)
        {
            hrManager.ReturnItems(userId, itemIds);
            return Json("");
        }
        public ActionResult CardSelect(Guid? id = null)
        {
            var user = userManager.GetAllUsers().FirstOrDefault();
            var model = itemManager.GetItemsByUserId(user.UserId);
            return View(model);
        }
        public PartialViewResult SelectItem(ItemModel model)
        {
            return PartialView(model);
        }
    }
}

Sources/IKS/IKS/Controllers/UserController.cs
using IKS.BusinessLogic.Managers;
using IKS.Database;
using IKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKS.Controllers
{
    public class UserController : Controller
    {
        public IUserManager userManager { get; set; }
        public UserController(IUserManager userManager)
        {
            this.userManager = userManager;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddUser()
        {
            return RedirectToAction(nameof(Edit), new { id=Guid.Empty });
        }

        [ValidateAntiForgeryToken]
        public ActionResult SaveUser(UserModel user)
        {
            if(user.IsNew)
                return RedirectToAction(nameof(Edit), new { id = Guid.Empty });
            else
                return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            UserModel model;
            if (id.HasValue)
                model = userManager.GetUser(id.Value);
            else
                model = new UserModel();

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserModel model)
        {
            if (ModelState.IsValid)
            {
                userManager.Save(model);
            }
            return View(model);
        }
    }
}

Sources/IKS/IKS/Views/Shared/ModalLayout.cshtml
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body">
                    @RenderBody()
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="ModalOK()">OK</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

</div>

Sources/IKS/IKS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Item", "Index", "Item")</li>
                    <li>@Html.ActionLink("Handover", "Index", "HandoverReturn")</li>
                    <li>@Html.ActionLink("Concert", "Index", "Event")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/iks")
    @RenderSection("scripts", required: false)
    <script src="~/MVCGridHandler.axd/script.js"></script>
</body>
</html>